# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - run: mkdir -p bin

    - name: Build
      run: go build -o bin/main -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
          name: binary file
          path: bin/main
